{{- if .Values.filebeat.enabled }}
{{- $elasticsearchServiceName := printf "%s-%s" .Release.Name "elasticsearch" | trunc 63 -}}
{{- $kibanaServiceName := printf "%s-%s" .Release.Name "elasticsearch-kibana" | trunc 63 -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-filebeat-daemonset-config
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    kubernetes.io/cluster-service: "true"
data:
  filebeat.yml: |-
    name: ${NODE_NAME}
    fields:
      nodePool: ${POOL_NAME}
    
    queue.mem:
      events: 4096
      flush:
        min_events: 512
        timeout: 10s

    filebeat.prospectors:
      - type: docker
        containers.ids:
        - "*"
        processors:
          - add_kubernetes_metadata:
              in_cluster: true

    processors:
      - add_cloud_metadata:

    output.elasticsearch:
      hosts: ['http://{{ $elasticsearchServiceName }}:{{ .Values.service.httpPort }}']
    
    {{- if .Values.kibana.enabled }}      
    setup.kibana.host: "http://{{ $kibanaServiceName }}:{{ .Values.kibana.httpPort }}"
    setup.dashboards.enabled: {{ .Values.filebeat.setupDashboards }}
    {{- end }}
{{- end }}