{{- $elasticsearchServiceName := printf "%s-%s" .Release.Name "elasticsearch" | trunc 63 -}}
{{- $redisServiceName := printf "%s-%s" .Release.Name "elasticsearch-redis" | trunc 63 -}}
{{- $kibanaServiceName := printf "%s-%s" .Release.Name "elasticsearch-kibana" | trunc 63 -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-logstash-config
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    kubernetes.io/cluster-service: "true"
data:
  beats.conf: |-
    input {
      beats {
        port => {{ .Values.logstash.beatsPort }}
        tags => 'beats'
      }

      http {
        type => 'http.in'
        port => '80'
        codec => 'json'
        tags => 'http.in'
      }
    }
    filter {
      if 'beats' in [tags] {
        ruby {
          init => "require 'time'"
          code => "event.cancel if Time.now.to_i - event.get('@timestamp').to_i > 600"
        }
        if [type] == "http" {
          json {
            source => "[http][response][body]"
            target => "[@metadata][elasticsearch_response]"
            skip_on_invalid_json => true
          }
          mutate {
            copy => { "[@metadata][elasticsearch_response][took]" => "[http][response][fields][took]" }
          }
        }
      }
    }
    output {
      if 'beats' in [tags] {
        elasticsearch {
          hosts => "http://{{ $elasticsearchServiceName }}:{{ .Values.service.httpPort }}"
          manage_template => false
          index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
        }
      } else if [index] {
        elasticsearch {
          hosts => "http://{{ $elasticsearchServiceName }}:{{ .Values.service.httpPort }}"
          manage_template => true
          index => "logstash-%{[index]}-%{+YYYY.MM.dd}"
        }
      } else {
        elasticsearch {
          hosts => "http://{{ $elasticsearchServiceName }}:{{ .Values.service.httpPort }}"
          manage_template => true
          index => "logstash-unknown-%{+YYYY.MM.dd}"
        }
      }
    }
