{{- if .Values.metricbeat.enabled }}
# Deploy singleton instance in the whole cluster for some unique data sources, like kube-state-metrics
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-metricbeat
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: metricbeat
        image: "{{ .Values.metricbeat.image.repository }}:{{ .Values.metricbeat.image.tag }}"
        args: [
          "-c", "/etc/metricbeat.yml",
          "-e",
        ]
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
        resources:
{{ toYaml .Values.metricbeat.resources | indent 10 }}
        volumeMounts:
        - name: config
          mountPath: /etc/metricbeat.yml
          readOnly: true
          subPath: metricbeat.yml
        - name: modules
          mountPath: /usr/share/metricbeat/modules.d
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: {{ template "fullname" . }}-metricbeat-config
      - name: modules
        configMap:
          defaultMode: 0600
          name: {{ template "fullname" . }}-metricbeat-deployment-modules
{{- end }}