{{- $elasticsearchServiceName := printf "%s-%s" .Release.Name "elasticsearch" | trunc 63 -}}
{{- $logstashServiceName := printf "%s-%s" .Release.Name "elasticsearch-logstash" | trunc 63 -}}
{{- $redisServiceName := printf "%s-%s" .Release.Name "elasticsearch-redis" | trunc 63 -}}
{{- $kibanaServiceName := printf "%s-%s" .Release.Name "elasticsearch-kibana" | trunc 63 -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-metricbeat-deployment-config
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    kubernetes.io/cluster-service: "true"
data:
  metricbeat-config: |-
    name: ${NODE_NAME}
    
    max_start_delay: {{ .Values.beats.max_start_delay }}

    queue.mem:
      events: {{ .Values.beats.queue.events }}
      flush:
        min_events: {{ .Values.beats.queue.min_events }}
        timeout: {{ .Values.beats.queue.timeout }}

    metricbeat.modules:
      - module: kubernetes
        metricsets:
          - state_node
          - state_deployment
          - state_replicaset
          - state_pod
          - state_container
          # Uncomment this to get k8s events:
          - event
        period: 30s
        hosts: ["kube-state-metrics.kube-system.svc.cluster.local:8080"]

    logging.metrics.enabled: false

    processors:
      - add_cloud_metadata: ~

    {{- if .Values.logstash.enabled }}
    output.logstash:
      hosts: ['{{ $logstashServiceName }}:{{ .Values.logstash.beatsPort }}']
      bulk_max_size: {{ .Values.beats.output.max_bulk_size }}
      slow_start: true
    {{- else if .Values.redis.enabled }}
    output.redis:
      hosts: ['{{ $redisServiceName }}:{{ .Values.redis.port }}']
      bulk_max_size: {{ .Values.beats.output.max_bulk_size }}
    {{- else }}
    output.elasticsearch:
      hosts: ['http://{{ $elasticsearchServiceName }}:{{ .Values.service.httpPort }}']
      bulk_max_size: {{ .Values.beats.output.max_bulk_size }}
    {{- end }}
    
    {{- if .Values.kibana.enabled }}      
    setup.kibana.host: "http://{{ $kibanaServiceName }}:{{ .Values.kibana.httpPort }}"
    setup.dashboards.enabled: {{ .Values.metricbeat.setupDashboards }}
    {{- end }}
