{{- if .Values.packetbeat.enabled }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "fullname" . }}-packetbeat
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
        kubernetes.io/cluster-service: "true"
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: packetbeat
        image: "{{ .Values.packetbeat.image.repository }}:{{ .Values.packetbeat.image.tag }}"
        imagePullPolicy: {{ .Values.packetbeat.image.pullPolicy }}
        command:
        - /bin/sh
        - -c
        - export POOL_NAME=$(echo $NODE_NAME | sed "s/^gke-main-\(.*\)-.*-.*$/\1/")
          && /usr/share/packetbeat/packetbeat -e -c /etc/packetbeat.yml
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
          capabilities:
            add:
            - NET_ADMIN
        resources:
{{ toYaml .Values.packetbeat.resources | indent 10 }}
        volumeMounts:
        - name: config
          mountPath: /etc/packetbeat.yml
          readOnly: true
          subPath: packetbeat.yml
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: {{ template "fullname" . }}-packetbeat-daemonset-config
      - name: data
        emptyDir: {}
{{- end }}